# Generated by Django 6.0.3 on 2026-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='stripe_meta_data',
            field=models.JSONField(null=True),
        ),
    ]
